{"time":"2024-11-25T19:48:32.5243513+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-25T19:48:32.5243513+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241125_194832-ypwpb45k\\logs\\debug-core.log"}
{"time":"2024-11-25T19:48:32.651087+01:00","level":"INFO","msg":"created new stream","id":"ypwpb45k"}
{"time":"2024-11-25T19:48:32.651087+01:00","level":"INFO","msg":"stream: started","id":"ypwpb45k"}
{"time":"2024-11-25T19:48:32.651087+01:00","level":"INFO","msg":"sender: started","stream_id":"ypwpb45k"}
{"time":"2024-11-25T19:48:32.651087+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"ypwpb45k"}}
{"time":"2024-11-25T19:48:32.651087+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"ypwpb45k"}}
{"time":"2024-11-25T19:48:32.9361619+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-25T19:48:52.9414147+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 32248"}
{"time":"2024-11-27T07:57:35.5222617+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"time":"2024-11-27T07:57:37.5326091+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:19.777602+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:22.2004569+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:26.9792954+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T23:24:10.5462006+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream"}
{"time":"2024-11-28T21:00:40.196651+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-28T22:45:40.1587811+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-29T02:30:40.1876813+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-29T09:15:38.38535+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ypwpb45k/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
