{"time":"2024-11-22T20:03:14.4704802+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-22T20:03:14.4704802+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241122_200314-k76cvfmh\\logs\\debug-core.log"}
{"time":"2024-11-22T20:03:14.5956441+01:00","level":"INFO","msg":"created new stream","id":"k76cvfmh"}
{"time":"2024-11-22T20:03:14.5956441+01:00","level":"INFO","msg":"stream: started","id":"k76cvfmh"}
{"time":"2024-11-22T20:03:14.5956441+01:00","level":"INFO","msg":"sender: started","stream_id":"k76cvfmh"}
{"time":"2024-11-22T20:03:14.5956441+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"k76cvfmh"}}
{"time":"2024-11-22T20:03:14.5956441+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"k76cvfmh"}}
{"time":"2024-11-22T20:03:15.0002383+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-22T20:04:25.0042169+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 24016"}
{"time":"2024-11-23T06:15:36.5344769+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-24T09:31:07.6342767+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-24T09:31:09.7361342+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-24T17:27:51.5745099+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-24T17:27:53.5841507+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-25T07:45:38.467527+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-27T07:57:35.5222617+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": context deadline exceeded"}
{"time":"2024-11-27T07:57:37.9628962+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:19.5450874+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:21.907879+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:26.8722781+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:35.1423235+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T19:30:15.0435546+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream"}
{"time":"2024-11-29T03:00:39.6584355+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-29T11:02:31.9856668+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/k76cvfmh/file_stream"}
