{"time":"2024-11-16T15:28:37.8818508+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-16T15:28:37.8818508+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\diabetic_retinopathy\\wandb\\run-20241116_152837-wbgs8uly\\logs\\debug-core.log"}
{"time":"2024-11-16T15:28:38.0076391+01:00","level":"INFO","msg":"created new stream","id":"wbgs8uly"}
{"time":"2024-11-16T15:28:38.0076391+01:00","level":"INFO","msg":"stream: started","id":"wbgs8uly"}
{"time":"2024-11-16T15:28:38.0076391+01:00","level":"INFO","msg":"sender: started","stream_id":"wbgs8uly"}
{"time":"2024-11-16T15:28:38.0076391+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"wbgs8uly"}}
{"time":"2024-11-16T15:28:38.0076391+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"wbgs8uly"}}
{"time":"2024-11-16T15:28:38.2911886+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-16T15:41:28.2964099+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 19904"}
{"time":"2024-11-16T20:30:39.3432085+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/wbgs8uly/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-17T07:30:37.578494+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/wbgs8uly/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
