{"time":"2024-11-30T14:56:20.5110075+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-30T14:56:20.5110075+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241130_145620-cv5qan43\\logs\\debug-core.log"}
{"time":"2024-11-30T14:56:20.6363957+01:00","level":"INFO","msg":"created new stream","id":"cv5qan43"}
{"time":"2024-11-30T14:56:20.6363957+01:00","level":"INFO","msg":"stream: started","id":"cv5qan43"}
{"time":"2024-11-30T14:56:20.6363957+01:00","level":"INFO","msg":"sender: started","stream_id":"cv5qan43"}
{"time":"2024-11-30T14:56:20.6363957+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"cv5qan43"}}
{"time":"2024-11-30T14:56:20.6363957+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"cv5qan43"}}
{"time":"2024-11-30T14:56:20.9995529+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-30T14:56:41.0260345+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 23940"}
{"time":"2024-12-01T08:27:50.6277109+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-01T08:27:53.0056671+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-01T15:28:38.5499144+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": read tcp 192.168.0.102:62072->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-02T09:27:03.7587645+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-02T09:27:06.132567+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T09:14:20.5682469+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T09:14:23.0366323+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T10:15:38.547597+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-03T15:00:39.7592338+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-03T15:19:19.8127009+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/cv5qan43/file_stream\": read tcp 192.168.0.102:49811->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
